### ISSUE TITLE
[Enhancement] Option to not use date filter

### ISSUE THREAD

**Issue by jmpoastUP** [giranm/pd-live-react#30]
Our operations support group would like to, by default, see all open tickets and not select a 'since' date. Can we add an option to not use the date filter? I tried clearing out the date but that didn't work.

**Comment by jmpoastUP** [comment]
In addition, the date filter doesn't seem to cache like the rest of the filters and we have to re-set it each time we reload the page. Can we get it to cache?

**Comment by giranm** [comment]
Having reviewed this enhancement, there are a few considerations here:

- PagerDuty [`/incidents`](https://developer.pagerduty.com/api-reference/b3A6Mjc0ODEzOA-list-incidents) API endpoint has a default `since` date of 1 month, going back as far as 6 months.
  No incidents can be returned which are older than 6 months.
- Querying large number incidents (+1000) in the query can impact user experience; this is a larger issue to be addressed by: #52
- Typically large number of incidents are returned when querying for `resolved` state; users should consider PagerDuty's core [Search](https://support.pagerduty.com/docs/search) for deeper search capabilities on a larger dataset.

Removing the since date filter in the UI will default back to a 1 month lookback, so a good middleground here is to make the since date filter a configurable item.

e.g. Users can set the default lookback to "6M" which means the since data will be set to 6 months before the current date.

**Comment by giranm** [comment]
Given the above feedback and the proposed solution implemented by #56, this issue will now be closed.
