### ISSUE TITLE
[Bug] Search bar doesn't work

### ISSUE THREAD

**Issue by jmpoastUP** [giranm/pd-live-react#42]
Entering text into the search bar in PDLive simply turns the search bar yellow and doesn't filter any of the results.

**Comment by giranm** [comment]
Search is powered by [Fuse.js](https://fusejs.io/api/options.html) which has the following options defined below:

https://github.com/giranm/pd-live-react/blob/6a9901e8bbd56714a5421f08765983519ae5663c/src/config/fuse-config.js#L8

As part of my initial testing, I decided to enable `useExtendedSearch` and set `threshold: 1` so that regex based searching was enabled. This probably hindered the original intention to implement a fuzzy-based search on the incidents dataset.

Setting `threshold: 0.6` (i.e. default) should have the desired effect of having a fuzzy search.
