### ISSUE TITLE
[Enhancement] Ability to view all incidents associated to a team

### ISSUE THREAD

**Issue by jmpoastUP** [giranm/pd-live-react#80]
Currently the team filter only shows incidents directly assigned to the team. We would like to assign these incidents to the application team directly and add our command center as additional responders so they are aware and can track the issue in their PDLive console but not be the primary assigned team. For that to work we would need the team filter to also show incidents where the team is added as an additional responder.

**Comment by giranm** [comment]
Hi @jmpoastUP,

As you are aware, the teams filter applies a query to our API such that it returns incidents which have direct team assignment (based on escalation policy or user). Due to our current data model, adding a responder request does not populate the team assignment in the incident object (thus you cannot filter by this).

On initial inspection, there are some options for workarounds - mainly updating the associated escalation policy to include the operations team for visibility purposes.

There is also another angle of including the responder requests as an additional column, then using the global search functionality to do any further matches.

e.g. you can decide to filter by team assignment, then search/sort for "operations" to see incidents you've been added to as a responder.

**Comment by giranm** [comment]
Hi @jmpoastUP,

Circling back to our previous discussions over email, the optimal solution here would be to wait for PagerDuty's custom incident fields to become available, which you can then update with any specific metadata to populate your view.

e.g. have a field for "shadow team", mark the additional team, then search/filter for this field in PD Live.

I will close this issue and will track upcoming enhancements on future tickets.

Thanks, Giran.
